project_id = "foiojihgpeehvpwejeqw"

[functions]

[functions.andar-bahar-game-manager]
verify_jwt = false

[[cron.andar-bahar-auto-manage]]
function_name = "andar-bahar-game-manager"
cron = "*/10 * * * * *"  # Every 10 seconds
query_parameters = { action = "auto_manage" }