project_id = "foiojihgpeehvpwejeqw"

[functions]

[functions.andar-bahar-game-manager]
verify_jwt = false

[[cron.andar-bahar-auto-manage]]
function_name = "andar-bahar-game-manager"
cron = "*/10 * * * * *"  # Every 10 seconds
query_parameters = { action = "auto_manage" }

[functions.create-admin-user]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.get-team-members]
verify_jwt = true

[functions.sports-proxy]
verify_jwt = false

[functions.sports-rapidapi]
verify_jwt = false

[functions.sports-rapidapi-odds]
verify_jwt = false

[functions.sports-diamond-proxy]
verify_jwt = false

[functions.sports-fallback-proxy]
verify_jwt = false

[functions.ludo-game-manager]
verify_jwt = true